# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: debian:sid-slim

before_script:
  - apt update
  - apt -y install hugo

test:
  script:
  - hugo
  - ls -la
  except:
    - master

pages:
  script:
  - rm -rvf resources public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
