baseURL = "https://wiki2.luebeck.freifunk.net"
languageCode = "en-us"
title = "FFHL Wiki"
theme = "hugo-book"


[params]
BookRepo = "https://gitlab.com/freifunk-luebeck/ffhl-wiki"
BookEditPath = "-/blob/master/content/"
BookLogo = "/logo.svg"
BookSection = "docs"
BookComments = true
BookPortableLinks = true
BookMenuBundle = "/menu"
